//bank managment app 
function createBank(bankName,bankCode,bankAddress,bankBranches,helpline,numOfATM){
    this.bankName = bankName
    this.bankCode = bankCode
    this.bankAddress = bankAddress
    this.bankBranches = bankBranches
    this.listOfUsers = []
    this.helpline = helpline;
    this.numOfATM = numOfATM;
    this.userBalance = function(){

    }
    this.userDeposit = function() {
        
    }
    this.totalBalanceInBank = function() {
        
    }
    this.userStatus = function() {
        
    }
    this.userWithdrawl = function(){

    }
}